// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Minecraft.Data;

#nullable disable

namespace Minecraft.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Minecraft.Models.GameMode", b =>
                {
                    b.Property<int>("ModeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("ModeID");

                    b.ToTable("GameModes");

                    b.HasData(
                        new
                        {
                            ModeID = 1,
                            Description = "Gather resources, maintain health, and survive against monsters.",
                            ModeName = "Survival"
                        },
                        new
                        {
                            ModeID = 2,
                            Description = "Unlimited resources to build and create without restrictions.",
                            ModeName = "Creative"
                        },
                        new
                        {
                            ModeID = 3,
                            Description = "Play custom maps and adventures created by other players.",
                            ModeName = "Adventure"
                        });
                });

            modelBuilder.Entity("Minecraft.Models.Item", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemID");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            ItemID = 1,
                            ImageURL = "apple.png",
                            ItemName = "Apple",
                            ItemType = "Food",
                            Price = 10
                        },
                        new
                        {
                            ItemID = 2,
                            ImageURL = "sword.png",
                            ItemName = "Sword",
                            ItemType = "Weapon",
                            Price = 100
                        },
                        new
                        {
                            ItemID = 3,
                            ImageURL = "axe.png",
                            ItemName = "Axe",
                            ItemType = "Tool",
                            Price = 80
                        });
                });

            modelBuilder.Entity("Minecraft.Models.Monster", b =>
                {
                    b.Property<int>("MonsterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttackDamage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Health")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MonsterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("MonsterID");

                    b.ToTable("Monsters");

                    b.HasData(
                        new
                        {
                            MonsterID = 1,
                            AttackDamage = 5,
                            Health = 20,
                            MonsterName = "Zombie"
                        },
                        new
                        {
                            MonsterID = 2,
                            AttackDamage = 7,
                            Health = 15,
                            MonsterName = "Skeleton"
                        },
                        new
                        {
                            MonsterID = 3,
                            AttackDamage = 20,
                            Health = 10,
                            MonsterName = "Creeper"
                        });
                });

            modelBuilder.Entity("Minecraft.Models.MonsterKill", b =>
                {
                    b.Property<int>("KillID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("KillTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("MonsterID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RewardExp")
                        .HasColumnType("INTEGER");

                    b.HasKey("KillID");

                    b.HasIndex("MonsterID");

                    b.HasIndex("PlayerID");

                    b.ToTable("MonsterKills");

                    b.HasData(
                        new
                        {
                            KillID = 1,
                            KillTime = new DateTime(2025, 10, 10, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            MonsterID = 1,
                            PlayerID = 1,
                            RewardExp = 50
                        },
                        new
                        {
                            KillID = 2,
                            KillTime = new DateTime(2025, 10, 11, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            MonsterID = 2,
                            PlayerID = 2,
                            RewardExp = 70
                        },
                        new
                        {
                            KillID = 3,
                            KillTime = new DateTime(2025, 10, 12, 18, 15, 0, 0, DateTimeKind.Unspecified),
                            MonsterID = 3,
                            PlayerID = 3,
                            RewardExp = 100
                        });
                });

            modelBuilder.Entity("Minecraft.Models.Player", b =>
                {
                    b.Property<int>("PlayerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("ExperiencePoints")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModeID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("WalletBalance")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlayerID");

                    b.HasIndex("ModeID");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            PlayerID = 1,
                            CharacterName = "Nam Mai",
                            Email = "nammv1402@gmail.com",
                            ExperiencePoints = 1500,
                            ModeID = 1,
                            Password = "password123",
                            WalletBalance = 500
                        },
                        new
                        {
                            PlayerID = 2,
                            CharacterName = "Hello World",
                            Email = "helloworld0101@gmail.com",
                            ExperiencePoints = 1200,
                            ModeID = 2,
                            Password = "password456",
                            WalletBalance = 300
                        },
                        new
                        {
                            PlayerID = 3,
                            CharacterName = "One Above All",
                            Email = "oneaboveall999@gmail.com",
                            ExperiencePoints = 2000,
                            ModeID = 3,
                            Password = "password789",
                            WalletBalance = 800
                        });
                });

            modelBuilder.Entity("Minecraft.Models.PlayerQuest", b =>
                {
                    b.Property<int>("PlayerQuestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("PlayerQuestID");

                    b.HasIndex("PlayerID");

                    b.HasIndex("QuestID");

                    b.ToTable("PlayerQuests");

                    b.HasData(
                        new
                        {
                            PlayerQuestID = 1,
                            PlayerID = 1,
                            QuestID = 1,
                            Status = "In Progress"
                        },
                        new
                        {
                            PlayerQuestID = 2,
                            PlayerID = 2,
                            QuestID = 2,
                            Status = "Completed"
                        },
                        new
                        {
                            PlayerQuestID = 3,
                            PlayerID = 3,
                            QuestID = 3,
                            Status = "Not Started"
                        });
                });

            modelBuilder.Entity("Minecraft.Models.Purchase", b =>
                {
                    b.Property<int>("PurchaseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ItemID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VehicleID")
                        .HasColumnType("INTEGER");

                    b.HasKey("PurchaseID");

                    b.HasIndex("ItemID");

                    b.HasIndex("PlayerID");

                    b.HasIndex("VehicleID");

                    b.ToTable("Purchases");

                    b.HasData(
                        new
                        {
                            PurchaseID = 1,
                            Amount = 5,
                            ItemID = 1,
                            PlayerID = 1,
                            PurchaseDate = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PurchaseID = 2,
                            Amount = 1,
                            PlayerID = 2,
                            PurchaseDate = new DateTime(2025, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VehicleID = 2
                        },
                        new
                        {
                            PurchaseID = 3,
                            Amount = 2,
                            ItemID = 3,
                            PlayerID = 3,
                            PurchaseDate = new DateTime(2025, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Minecraft.Models.Quest", b =>
                {
                    b.Property<int>("QuestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("RewardExp")
                        .HasColumnType("INTEGER");

                    b.HasKey("QuestID");

                    b.ToTable("Quests");

                    b.HasData(
                        new
                        {
                            QuestID = 1,
                            Description = "Gather 10 pieces of wood from trees.",
                            QuestName = "Collect Wood",
                            RewardExp = 100
                        },
                        new
                        {
                            QuestID = 2,
                            Description = "Eliminate 5 zombies in the night.",
                            QuestName = "Defeat Zombies",
                            RewardExp = 200
                        },
                        new
                        {
                            QuestID = 3,
                            Description = "Construct a basic shelter to survive the night.",
                            QuestName = "Build a Shelter",
                            RewardExp = 150
                        });
                });

            modelBuilder.Entity("Minecraft.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VehicleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("VehicleID");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            VehicleID = 1,
                            ImageURL = "horse.png",
                            Price = 200,
                            VehicleName = "Horse",
                            VehicleType = "Mount"
                        },
                        new
                        {
                            VehicleID = 2,
                            ImageURL = "boat.png",
                            Price = 150,
                            VehicleName = "Boat",
                            VehicleType = "Watercraft"
                        },
                        new
                        {
                            VehicleID = 3,
                            ImageURL = "minecart.png",
                            Price = 300,
                            VehicleName = "Minecart",
                            VehicleType = "Rail Transport"
                        });
                });

            modelBuilder.Entity("Minecraft.Models.MonsterKill", b =>
                {
                    b.HasOne("Minecraft.Models.Monster", "Monster")
                        .WithMany("MonsterKills")
                        .HasForeignKey("MonsterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Minecraft.Models.Player", "Player")
                        .WithMany("MonsterKills")
                        .HasForeignKey("PlayerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Monster");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Minecraft.Models.Player", b =>
                {
                    b.HasOne("Minecraft.Models.GameMode", "GameMode")
                        .WithMany("Players")
                        .HasForeignKey("ModeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameMode");
                });

            modelBuilder.Entity("Minecraft.Models.PlayerQuest", b =>
                {
                    b.HasOne("Minecraft.Models.Player", "Player")
                        .WithMany("PlayerQuests")
                        .HasForeignKey("PlayerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Minecraft.Models.Quest", "Quest")
                        .WithMany("PlayerQuests")
                        .HasForeignKey("QuestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Quest");
                });

            modelBuilder.Entity("Minecraft.Models.Purchase", b =>
                {
                    b.HasOne("Minecraft.Models.Item", "Item")
                        .WithMany("Purchases")
                        .HasForeignKey("ItemID");

                    b.HasOne("Minecraft.Models.Player", "Player")
                        .WithMany("Purchases")
                        .HasForeignKey("PlayerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Minecraft.Models.Vehicle", "Vehicle")
                        .WithMany("Purchases")
                        .HasForeignKey("VehicleID");

                    b.Navigation("Item");

                    b.Navigation("Player");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Minecraft.Models.GameMode", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("Minecraft.Models.Item", b =>
                {
                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("Minecraft.Models.Monster", b =>
                {
                    b.Navigation("MonsterKills");
                });

            modelBuilder.Entity("Minecraft.Models.Player", b =>
                {
                    b.Navigation("MonsterKills");

                    b.Navigation("PlayerQuests");

                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("Minecraft.Models.Quest", b =>
                {
                    b.Navigation("PlayerQuests");
                });

            modelBuilder.Entity("Minecraft.Models.Vehicle", b =>
                {
                    b.Navigation("Purchases");
                });
#pragma warning restore 612, 618
        }
    }
}
